### ISSUE TITLE
Setup failed for custom integration 'daikin_madoka': Unable to import component: cannot import name 'discover' from 'bleak'

### ISSUE THREAD

**Issue by peponline86** [mduran80/daikin_madoka#62]
Worked before, but it got broken when I updated HA to 2025.8.2.

> Logger: homeassistant.setup Bron: setup.py:343 Eerst voorgekomen: 21:59:32 (1 gebeurtenis) Laatst gelogd: 21:59:32 Setup failed for custom integration 'daikin_madoka': Unable to import component: cannot import name 'discover' from 'bleak' (/usr/local/lib/python3.13/site-packages/bleak/__init__.py) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/loader.py", line 1003, in async_get_component comp = await self.hass.async_add_import_executor_job( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ self._get_component, True ^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path) ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/daikin_madoka_backup2/__init__.py", line 6, in <module> from pymadoka import Controller, discover_devices, force_device_disconnect File "/usr/local/lib/python3.13/site-packages/pymadoka/__init__.py", line 1, in <module> from .controller import Controller File "/usr/local/lib/python3.13/site-packages/pymadoka/controller.py", line 8, in <module> from pymadoka.feature import Feature, NotImplementedException File "/usr/local/lib/python3.13/site-packages/pymadoka/feature.py", line 11, in <module> from pymadoka.connection import Connection, ConnectionException, ConnectionStatus File "/usr/local/lib/python3.13/site-packages/pymadoka/connection.py", line 12, in <module> from bleak import BleakClient,BleakScanner,discover ImportError: cannot import name 'discover' from 'bleak' (/usr/local/lib/python3.13/site-packages/bleak/__init__.py) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component component = await integration.async_get_component() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 1023, in async_get_component self._component_future.result() ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1063, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path) ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/daikin_madoka_backup2/__init__.py", line 6, in <module> from pymadoka import Controller, discover_devices, force_device_disconnect File "/usr/local/lib/python3.13/site-packages/pymadoka/__init__.py", line 1, in <module> from .controller import Controller File "/usr/local/lib/python3.13/site-packages/pymadoka/controller.py", line 8, in <module> from pymadoka.feature import Feature, NotImplementedException File "/usr/local/lib/python3.13/site-packages/pymadoka/feature.py", line 11, in <module> from pymadoka.connection import Connection, ConnectionException, ConnectionStatus File "/usr/local/lib/python3.13/site-packages/pymadoka/connection.py", line 12, in <module> from bleak import BleakClient,BleakScanner,discover ImportError: cannot import name 'discover' from 'bleak' (/usr/local/lib/python3.13/site-packages/bleak/__init__.py)

Got a workaround by changing a line in connections.py in pymadoka.
Find this file in /usr/local/lib/python3.x/site-packages/pymadoka/connection.py (had to docker exec into it to find this file).
Replace `from bleak import BleakClient,BleakScanner,discover` with `from bleak import BleakClient, BleakScanner`, restart your HA and you're good to go for now.

**Comment by davidbarredo** [comment]
Checkout a temporary fix: https://github.com/mduran80/daikin_madoka/issues/61#issuecomment-3711003709
